<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="0" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-29T18:44:57 IST" name="API Regression Suite" finished-at="2024-02-29T18:44:59 IST" duration-ms="2021">
    <groups>
    </groups>
    <test started-at="2024-02-29T18:44:57 IST" name="Go Rest API Create User Test" finished-at="2024-02-29T18:44:59 IST" duration-ms="2021">
      <class name="tests.CreateUserTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:57 IST" name="setup" finished-at="2024-02-29T18:44:58 IST" duration-ms="902" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in]]>
              </value>
            </param>
          </params>
          <exception class="frameworkexception.FrameworkException">
            <message>
              <![CDATA[please pass the correct envname:: qa]]>
            </message>
            <full-stacktrace>
              <![CDATA[frameworkexception.FrameworkException: please pass the correct envname:: qa
at configuration.ConfigurationManager.initProp(ConfigurationManager.java:44)
at base.BaseTest.setup(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- frameworkexception.FrameworkException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="createObject()[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:59 IST" name="createObject" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1709212499757" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createObject -->
        <test-method signature="createUser(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:59 IST" name="createUser" data-provider="getUserData" finished-at="2024-02-29T18:44:59 IST" duration-ms="0" status="SKIP">
          <exception class="frameworkexception.FrameworkException">
            <message>
              <![CDATA[please pass the correct envname:: qa]]>
            </message>
            <full-stacktrace>
              <![CDATA[frameworkexception.FrameworkException: please pass the correct envname:: qa
at configuration.ConfigurationManager.initProp(ConfigurationManager.java:44)
at base.BaseTest.setup(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- frameworkexception.FrameworkException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method is-config="true" signature="createObject()[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:59 IST" name="createObject" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1709212499803" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createObject -->
        <test-method signature="createUser(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:59 IST" name="createUser" data-provider="getUserData" finished-at="2024-02-29T18:44:59 IST" duration-ms="0" status="SKIP">
          <exception class="frameworkexception.FrameworkException">
            <message>
              <![CDATA[please pass the correct envname:: qa]]>
            </message>
            <full-stacktrace>
              <![CDATA[frameworkexception.FrameworkException: please pass the correct envname:: qa
at configuration.ConfigurationManager.initProp(ConfigurationManager.java:44)
at base.BaseTest.setup(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- frameworkexception.FrameworkException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method is-config="true" signature="createObject()[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:59 IST" name="createObject" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1709212499816" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createObject -->
        <test-method signature="createUser(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:tests.CreateUserTest@282cb7c7]" started-at="2024-02-29T18:44:59 IST" name="createUser" data-provider="getUserData" finished-at="2024-02-29T18:44:59 IST" duration-ms="0" status="SKIP">
          <exception class="frameworkexception.FrameworkException">
            <message>
              <![CDATA[please pass the correct envname:: qa]]>
            </message>
            <full-stacktrace>
              <![CDATA[frameworkexception.FrameworkException: please pass the correct envname:: qa
at configuration.ConfigurationManager.initProp(ConfigurationManager.java:44)
at base.BaseTest.setup(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- frameworkexception.FrameworkException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
      </class> <!-- tests.CreateUserTest -->
    </test> <!-- Go Rest API Create User Test -->
  </suite> <!-- API Regression Suite -->
</testng-results>
